stages:
    - test
    - deploy

test:
    stage: test
    image: eclipse-temurin:23-jdk-alpine
    script:
        - ./mvnw -Drevision=$CI_PIPELINE_ID --batch-mode --errors --settings settings.xml clean package -Dmaven.profile -Dmaven.compiler.proc=full
    variables:
        MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    cache:
        paths:
            - .m2/repository

deploy:
    stage: deploy
    image: eclipse-temurin:23-jdk-alpine
    script:
        - ./mvnw -Drevision=$CI_PIPELINE_ID --batch-mode --errors --settings settings.xml deploy -Dmaven.profile -DskipTests -Dmaven.compiler.proc=full
    variables:
        MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    cache:
        paths:
            - .m2/repository
    only:
        - main

