name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:23-jdk-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Maven
        run: echo "MAVEN_OPTS=-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$GITHUB_WORKSPACE/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true" >> $GITHUB_ENV
      - name: Build
        run: ./mvnw --batch-mode --errors --settings settings.xml clean compile -Dmaven.profile
      - name: Test
        run: ./mvnw --batch-mode --errors --settings settings.xml test -Dmaven.profile

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:23-jdk-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Release
        env:
          SONATYPE_TOKEN_USERNAME: ${{ secrets.SONATYPE_TOKEN_USERNAME }}
          SONATYPE_TOKEN_PASSWORD: ${{ secrets.SONATYPE_TOKEN_PASSWORD }}
        run: ./mvnw --batch-mode --errors --settings settings.xml deploy -DskipTests -Dmaven.profile
